# azure-pipelines.yml

trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  artifactFeed: 'NugetFeed'

jobs:
- job: BuildAndPublish
  pool:
    vmImage: 'windows-latest'
    parallel: 1
  steps:
  - task: DotNetCoreCLI@2
    displayName: 'Build Solution'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
    
  - task: DotNetCoreCLI@2
    displayName: 'Build and Pack NuGet Package'
    inputs:
      command: 'pack'
      projects: '**/*.csproj'
      versioningScheme: 'off'
      version: '1.0.0'  # Set your desired version number here
      includesymbols: true
      includesource: true

  - task: NuGetAuthenticate@0
    displayName: 'NuGet Authenticate'

  - task: NuGetCommand@2
    displayName: 'NuGet Publish'
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '$(artifactFeed)'
