# azure-pipelines.yml

trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  artifactFeed: 'bdrozd-new' # Replace with your feed name
  packageId: 'StringLibraryModified1' # New package ID to avoid conflicts
  packageVersion: '1.0.2' # Set your desired version number here

jobs:
- job: BuildAndPublish
  pool:
    vmImage: 'windows-latest'
    parallel: 1
  steps:
  - task: DotNetCoreCLI@2
    displayName: 'Build Solution'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
    
  - task: DotNetCoreCLI@2
    displayName: 'Build and Pack NuGet Package'
    inputs:
      command: 'pack'
      projects: '**/*.csproj'
      versioningScheme: 'off'
      version: $(packageVersion)
      includesymbols: true
      includesource: true
      arguments: '--configuration $(buildConfiguration) --package-id $(packageId)' # Use the modified package ID

  - task: NuGetAuthenticate@0
    displayName: 'NuGet Authenticate'

  - task: NuGetCommand@2
    displayName: 'NuGet Publish'
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: $(artifactFeed)
